### ISSUE TITLE
[9.0] Dependencia no encontrada

### ISSUE THREAD

**Issue by edser-pcg** [odoo-chile/l10n_cl_pos_credit_card_voucher#2]
Al tratar de instalar este módulo (descargado desde Odoo Apps) da un error, que aparenta ser una dependencia no encontrada.

El error es el siguiente:

Odoo Server Error
Traceback (most recent call last):
  File "/odoo/odoo-server/src/odoo/openerp/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/src/odoo/openerp/http.py", line 684, in dispatch
    result = self._call_function(*_self.params)
  File "/odoo/odoo-server/src/odoo/openerp/http.py", line 320, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/odoo/odoo-server/src/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/odoo/odoo-server/src/odoo/openerp/http.py", line 313, in checked_call
    result = self.endpoint(_a, *_kw)
  File "/odoo/odoo-server/src/odoo/openerp/http.py", line 963, in __call__
    return self.method(_args, *_kw)
  File "/odoo/odoo-server/src/odoo/openerp/http.py", line 513, in response_wrap
    response = f(_args, *_kw)
  File "/odoo/odoo-server/src/odoo/addons/web/controllers/main.py", line 901, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/src/odoo/addons/web/controllers/main.py", line 889, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/odoo/odoo-server/src/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/odoo/odoo-server/src/odoo/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/odoo/odoo-server/src/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/odoo/odoo-server/src/odoo/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/odoo/odoo-server/src/odoo/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/src/odoo/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/odoo/odoo-server/src/odoo/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/odoo/odoo-server/src/odoo/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/odoo/odoo-server/src/odoo/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/odoo/odoo-server/src/odoo/openerp/tools/convert.py", line 851, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/odoo/odoo-server/src/odoo/openerp/tools/convert.py", line 938, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/odoo/odoo-server/src/odoo/openerp/tools/convert.py", line 801, in parse
    self.parse(rec, mode)
  File "/odoo/odoo-server/src/odoo/openerp/tools/convert.py", line 804, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/odoo/odoo-server/src/odoo/openerp/tools/convert.py", line 777, in _tag_template
    return self._tag_record(cr, record, data_node)
  File "/odoo/odoo-server/src/odoo/openerp/tools/convert.py", line 708, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/odoo/odoo-server/src/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/odoo/odoo-server/src/odoo/openerp/addons/base/ir/ir_model.py", line 1143, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/odoo/odoo-server/src/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/odoo/odoo-server/src/odoo/openerp/addons/base/ir/ir_ui_view.py", line 353, in create
    context=context)
  File "/odoo/odoo-server/src/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/odoo/odoo-server/src/odoo/openerp/api.py", line 354, in old_api
    result = method(recs, _args, *_kwargs)
  File "/odoo/odoo-server/src/odoo/openerp/models.py", line 4157, in create
    record = self.browse(self._create(old_vals))
  File "/odoo/odoo-server/src/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/odoo/odoo-server/src/odoo/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, _args, *_old_kwargs)
  File "/odoo/odoo-server/src/odoo/openerp/models.py", line 4354, in _create
    recs._validate_fields(vals)
  File "/odoo/odoo-server/src/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/odoo/odoo-server/src/odoo/openerp/models.py", line 1271, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "Invalid view definition

Detalles del error:
El elemento '<xpath expr="//link[@id='pos-stylesheet']">' no pudo ser ubicado en la vista padre

Error de contexto:
Vista `l10n_cl_pos_credit_card_voucher index`
[view_id: 1454, xml_id: n/a, model: n/a, parent_id: 1388]
None" while parsing None:11, near
<data name="l10n_cl_pos_credit_card_voucher index" inherit_id="point_of_sale.index">
            <xpath expr="//link[@id='pos-stylesheet']" position="after">
                <link rel="stylesheet" href="/l10n_cl_pos_credit_card_voucher/static/src/css/pos_cc_voucher.css"/>
            </xpath>
        </data>

**Comment by edser-pcg** [comment]
El error no aparecio completo más arriba, acá esta la ultima parte completa:

```

ParseError: "Invalid view definition

Detalles del error:
El elemento '<xpath expr="//link[@id='pos-stylesheet']">' no pudo ser ubicado en la vista padre

Error de contexto:
Vista `l10n_cl_pos_credit_card_voucher index`
[view_id: 1456, xml_id: n/a, model: n/a, parent_id: 1388]
None" while parsing None:11, near
<data name="l10n_cl_pos_credit_card_voucher index" inherit_id="point_of_sale.index">
            <xpath expr="//link[@id='pos-stylesheet']" position="after">
                <link rel="stylesheet" href="/l10n_cl_pos_credit_card_voucher/static/src/css/pos_cc_voucher.css"/>
            </xpath>
        </data>
```
